### ISSUE TITLE
First information card should be "What is depression?"

### ISSUE THREAD

**Issue by robert-johansson** [kandidatg11/behaviour-activation#76]
First information card (Before "Behavioral activation") should be "What is depression?" containing the below text:

# What is depression?

This treatment was designed to help you with depression, which is defined as an extended period of time of at least 2 weeks in which a person experiences a depressed mood or a loss of interest or pleasure in activities that were once enjoyed, along with several other symptoms. Many people will experience at least one episode of major depression in their lifetime and it can affect people of all ages, cultures, income, education, and marital status. Depression can have a major impact on your life, including decreased optimism or motivation, low self-esteem, trouble concentrating (paying attention), self-harm, and/or suicidal thoughts and behavior. Medical problems associated with depression include heart disease, chronic pain, type 2 diabetes, substance use, fatigue, and malnutrition. Individuals with depression often keep to themselves and avoid their normal activities. This isolation can cause additional problems, such as loneliness, relationship problems, decreased job satisfaction or unemployment, and educational failure. Given all these resulting problems, the identification and treatment of depression are critical.

The specific symptoms of depression may include the following:
* Feeling sad or down most of the time,
* Loss of interest in usual activities,
* Significant weight loss or weight gain,
* A decrease or increase in appetite,
* Difficulty sleeping or sleeping too much,
* Feelings of agitation or irritability,
* Feeling tired or loss of energy (fatigue),
* Feelings of worthlessness or excessive/inappropriate guilt,
* Difficulty thinking or concentrating or making decisions,
* Crying spells,
* Feeling hopeless,
* Suicidal thoughts and/or attempts.

Although most individuals experience some form of the above symptoms from time to time, a diagnosis of depression only is made if you feel strong feelings of distress, or you are having a lot of trouble with your day-to-day functioning. Some people can identify stressful life events including loss of a loved one, financial difficulty, or job loss as a reason for their depression. However, the specific causes of depression are rarely known, and depression might start without warning. Regardless of the initial cause of depression, depression results in a specific pattern of behavior that leads to feelings of loneliness, sadness, isolation, lack of purpose, and/or hopelessness. The key to feeling better is not in identifying the root cause of depression because this is nearly impossible, but rather in understanding and changing your depressed patterns of behavior.

**Comment by malin-mallan** [comment]
Do you want a swedish translation on this as well or just english?

**Comment by robert-johansson** [comment]
Yes, the app needs to be complete in both English and Swedish. You can use Google translate for now.
